### ISSUE TITLE
Add new bot responses

### ISSUE THREAD

**Issue by jac08h** [Jac08H/HahOrNahBot#1]
Add bot responses to _bot_responses/bot_responses.json_

**Comment by divayprakash** [comment]
@Jac08H Working on it!

**Comment by gunjan01** [comment]
@Jac08H Hi.  I would like to go ahead with this :)

**Comment by gunjan01** [comment]
@Jac08H  This is open right ? Or this is no more an issue ?

**Comment by jac08h** [comment]
Hey, I re-opened this issue  [here](https://github.com/Jac08H/HahOrNahBot/issues/5)
