### ISSUE TITLE
bot_responses.json having redundant declarations.

### ISSUE THREAD

**Issue by akashjobanputra** [Jac08H/HahOrNahBot#38]
The `joke_no_current` and `joke_new_try_again` arrays are declared twice, the first declaration has more options, so removal of second declaration will be a better choice for both the arrays.

https://github.com/jac08h/HahOrNahBot/blob/bc1d02a9c67b5b4d7e343d77da3d00435b67aea7/bot_responses/bot_responses.json#L74
And here:
https://github.com/jac08h/HahOrNahBot/blob/bc1d02a9c67b5b4d7e343d77da3d00435b67aea7/bot_responses/bot_responses.json#L100

Can be labelled as **Good-First-Issue** for new contributors.

**Comment by akashjobanputra** [comment]
Fix on Pull Request #39

**Comment by jac08h** [comment]
Merged #39, thank you!
